name: disaster-damage-assessment
channels:
  - conda-forge
dependencies:
  - python=3.7.9
  - pandas
  - matplotlib
  - scikit-learn
  - numpy=1.19.5
  - pip
  - pip:
    - tensorflow-addons[tensorflow]
    - ipykernel
    - wget
    - gradio
    - wandb
    - jinja2==2.11.2